DROP TABLE IF EXISTS pbs_qrtz_job;
DROP TABLE IF EXISTS pbs_qrtz_job_log;
-- 定时器信息表
CREATE TABLE `pbs_qrtz_job` (
  `ID` varchar(40) NOT NULL,
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CREATE_USER` varchar(30) DEFAULT NULL,
  `UPDATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATE_USER` varchar(30) DEFAULT NULL,
  `JOB_NAME` varchar(200) NOT NULL ,
  `IS_RUN` TINYINT(1) DEFAULT 0 COMMENT '0false不运行;1true运行',
  `IS_DEL` TINYINT(1) DEFAULT 0 COMMENT '0false未删除;1true删除',
  `JOB_TYPE` varchar(30) COMMENT '实现类型:JAVA,SQL',
  `JOB_IMP` varchar(20000) NOT NULL COMMENT '实现内容',
  `NIAN` varchar(10) DEFAULT NULL,
  `XINGQI` varchar(50) DEFAULT NULL,
  `YUE` varchar(50) DEFAULT NULL,
  `RI` varchar(50) DEFAULT NULL,
  `SHI` varchar(50) DEFAULT NULL,
  `FEN` varchar(50) DEFAULT NULL,
  `MIAO` varchar(50) DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT UNIQUE_JOB_NAME UNIQUE(JOB_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--定时器执行日志表
CREATE TABLE `pbs_qrtz_job_log` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CREATE_DATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATE_DATE` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `JOB_ID` varchar(60) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'pbs_qrtz_job表ID',
  `JOB_NAME` varchar(200) NOT NULL COMMENT 'pbs_qrtz_job表JOB_NAME',
  `JOB_GROUP` varchar(40) COMMENT '任务组名',
  `METHOD_NAME` varchar(40) NOT NULL COMMENT '任务方法',
  `METHOD_PARAMS` varchar(250) COMMENT '任务参数',
  `EXCUTE_TIME` int(11) DEFAULT NULL COMMENT '执行次数',
  `JOB_MSG` varchar(250) COMMENT '日志信息',
  `JOB_STATUS` varchar(10) NOT NULL COMMENT '执行状态',
  `EXCEP_MSG` varchar(400) COMMENT '异常信息',
  PRIMARY KEY (`ID`),
  KEY `JOB_INDEX` (`JOB_ID`,`JOB_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='执行日志表';